services:
  listener:
    build:
      context: ../..
      dockerfile: ./packages/listener/Dockerfile
    container_name: usher-listener
    environment:
      # Arangodb
      ARANGO_URL: http://usher:8529
      ARANGO_DATABASE: usher
      ARANGO_USERNAME: root
      ARANGO_PASSWORD: password
      # Ethereum
      PROVIDER_URL: http://usher:8545
      START_BLOCK: 1
      # Application
      LOG_LEVEL: debug
      restart: always
    networks:
      host: {}

networks:
  host:
    external: true
    name: host