version: "3.8"

services:
  db:
    container_name: usher_db
    image: arangodb/arangodb:${ARANGO_IMAGE_TAG:-3.9.2}
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    restart: unless-stopped
    ports:
      - ${ARANGO_PORT:-8529}:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
